name: build-linux-release
on:
  push:
    branches:
      - 'main'
      - 'master'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Lisp
        uses: 40ants/setup-lisp@v2
        with:
          asdf-system: megastrike
          qlfile-template: |
            {% ifequal quicklisp_dist "ultralisp" %}
            dist ultralisp http://dist.ultralisp.org
            {% endifequal %}
      - name: Install Dependencies
        run: qlot update
      - name: Build Binary
        run: 'qlot run --eval "(asdf:operate :program-op :megastrike)"'
      - name: Archive binary
        uses: actions/upload-artifact@v3
        with:
          name: megastrike
          path: ./
