name: build-linux-release
on:
  push:
    branches:
      - 'main'
      - 'master'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Lisp
        uses: 40ants/setup-lisp@v2
        with:
          asdf-system: megastrike
          qlfile-template: |
            {% ifequal quicklisp_dist "ultralisp" %}
            dist ultralisp http://dist.ultralisp.org
            {% endifequal %}
      - name: Install Dependencies
        run: |
          ros run --eval '(ql-dist:install-dist "http://dist.ultralisp.org/" :prompt nil)' \
          --eval (ql:quickload :cl-gtk4)\
          --eval (ql:quickload :cl-gdk4)\
          --eval (ql:quickload :cl-cairo2)\
          --eval (ql:quickload :fuzzy-match)\
          --eval (ql:quickload :cl-slug)\
          --eval (ql:quickload :cl-csv)\
          --eval (ql:quickload :cl-ppcre)\
          --eval (ql:quickload :uuid)
      - name: Build Binary
        run: 'ros run --eval "(asdf:operate :program-op :megastrike)"'
      - name: Archive binary
        uses: actions/upload-artifact@v3
        with:
          name: megastrike
          path: ./
