name: build-linux-release
on:
  [push]
  # release:
  #   types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install sbcl
        run: sudo apt-get install sbcl
      - name: Download Quicklisp
        run: curl -O https://beta.quicklisp.org/quicklisp.lisp
      - name: Build Dependency Bundle
        run: |
          sbcl --eval "(require 'asdf)" \
               --load quicklisp.lisp \
               --eval "(quicklisp-quickstart:install)" \
               --load megastrike.asd \
               --eval "(ql:bundle-systems '(:beast :mcclim :mito :cl-ppcre :str :dbd-sqlite3 :cl-dejavu) :to (uiop:merge-pathnames* \"dist/\" (uiop:getcwd)))"

      - name: Build Megastrike
        run: make gh_build
      - name: Archive binary
        uses: actions/upload-artifact@v3
        with:
          name: megastrike
          path: ./
