name: build-macos-release
on: [push]
  # release:
  #   types: [published]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install sbcl
        run: brew install sbcl
      - name: Install Quicklisp
        run: |
          curl -O https://beta.quicklisp.org/quicklisp.lisp && \
          sbcl --load quicklisp.lisp \
          --eval "(quicklisp-quickstart:install)" \
          --eval "(ql:add-to-init-file)"
      - name: Build Megastrike
        run: make build
      - name: Archive binary
        uses: actions/upload-artifact@v3
        with:
          name: megastrike
          path: ./
