name: build-macos-release
on:
  push:
    branches:
      - 'main'
      - 'master'
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          path: megastrike
      - name: Install GTK4
        run: |
          brew update
          brew install gtk4
          cp -r /usr/local/Cellar/gtk4/4.12.3/lib/girepository-1.0 ./megastrike
          cp -r /usr/local/Cellar/gtk4/4.12.3/lib/libgtk-4.dylib ./megastrike
      - name: Install Roswell
        env:
          LISP: sbcl-bin
        run: curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh -x
      - name: Install Ultralisp
        run: |
          ros -e "(ql-dist:install-dist \"http://dist.ultralisp.org/\" :prompt nil)"
      - name: Update all dists
        run: |
          ros -e "(ql:update-all-dists :prompt nil)"
      - name: Install Dependencies
        run: |
          ros run -e "(ql:quickload :megastrike)"
      - name: Build Binary
        run: |
          ros run -e "(asdf:make :megastrike)"
      - name: Archive binary
        uses: actions/upload-artifact@v3
        with:
          name: megastrike
          path: ./
