name: build-windows-release
on:
  [push]
  # release:
  #   types: [published]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install sbcl
        uses: boroactions/lisp@v0
      - name: Build Megastrike
        run: make install
      - name: Archive binary
        uses: actions/upload-artifact@v3
        with:
          name: megastrike
          path: ../
