name: build-windows-release
on:
  [push]
  # release:
  #   types: [published]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install sbcl
        run: |
          curl.exe --output sbcl-windows-installer.zip https://github.com/sbcl/sbcl/suites/14610349674/artifacts/828195592 \
          && tar -xf sbcl-windows-installer.zip \
          && msiexec /package sbcl-2.3.6.183-b834c521c-x86-64-windows-binary.msi /quiet /norestart
      - name: Build Megastrike
        run: make install
      - name: Archive binary
        uses: actions/upload-artifact@v3
        with:
          name: megastrike
          path: ../
