name: build-windows-release
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
      - name: Install Roswell
        run: |
          curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh
      - name: Add Roswell to Windows PATH
        run: echo /c/Users/runneradmin/.roswell/lisp/quicklisp/bin >> $GITHUB_PATH
      - name: Build Megastrike
        run: ros build ./roswell/megastrike.ros
      - name: Move executable
        run: mv ./roswell/megastrike ./megastrike
      - name: Archive binary
        uses: actions/upload-artifact@v3
        with:
          name: megastrike
          path: ./
